### PR TITLE
Add optional scheme and port in Host property, enabling support for SSL encrypted brokers

### PR DESCRIPTION
**Pull request by brudo**
Add support in the host property for optional scheme via tcp:// or ssl:// prefix and port via a :12345 suffix, with scheme defaulting to tcp:// and port defaulting to 1883 for TCP / 8883 for SSL. Remove port number property which becomes redundant with this change. (Could have added a boolean property for SSL instead, but this way makes it easier to apply the correct default port.)

### CODE REVIEW

**Comment by hanoch** [comment]
@brudo instead of ignoring the port property, can you rename the 'port' property to 'tcpPort' with a default of 1883 and add another 'sslPort' property with the default of 8883?
cc: @mzesri

**Comment by brudo** [comment]
@hanoch @mzesri  yes I can do that. In fact I already have the code. I'll offer that as a separate pull request and withdraw this one if the other is accepted.

**Comment by brudo** [comment]
See PR#7. It is roughly as you suggested. However I kept the non-encrypted port property just called port for compatibility with existing inputs defined against earlier versions. (Although, come to think of it, incrementing the version number to 10.5 already breaks old inputs.) Whichever of these is merged, I'll close tho other one.

**Comment by brudo** [comment]
A bit of housekeeping - I cherry-picked the additional two fixes / refinements that were committed on PR#7. So the two PRs are functionally identical except for the way the scheme and port are specified (in the URL vs. separate properties).

**Comment by hanoch** [comment]
@brudo I just merged PR #4, which is now causing new conflicts with PR #6 and PR #7.
Can you resolve the conflicts and figure out which approach you prefer - schema ports specified via the URL or separate properties.  We can even combine the two approcahes, start with the properties, and override with the URL, if specified.  Thoughts?
Please let me know when this #6 or #7 is ready to merge, so we will merge one of them and close the other.

**Comment by brudo** [comment]
That's the trouble with getting too far ahead and trying to keep the different changes in separate requests. I'll resolve the conflict and see about the combined approach as you suggest.

**Comment by brudo** [comment]
Conflicts are cleaned up in both branches. Now considering options to combine them. If we do combine them, I think I'd like to make it an error for port to be specified in both places. This implies the port property would be optional, with no default value. Defaults would be indicated in the help string.

**Comment by hanoch** [comment]
the transport port properties can act as the port default values (with an extra default level of a default value to property value as well, which we will hardcode to the defaults).  We can add the url props to allow for an override, but that might be an unnecessary overkill, if the URL is a propery by itself.  If that is the case we can drop the URL ports, and keep the port properties only.  thoughts?

**Comment by hanoch** [comment]
the opposite approach would be to remove the port properties altogether and keep the port part of the URL.  Any preference?

**Comment by brudo** [comment]
Yes; that is actually what is in this PR right now - port property was completely removed. That is actually my preference. Having two places to specify the port property can be confusing for end users, and also complicates the code and requires some trade-offs (e.g. port can't have blank default unless it's changed to a string, which isn't as nice).

However, if you preferred to retain the port property for backward compatibility then PR#7 is what I would recommend in that case, also just as it is.

The URL notation does lend itself to other capabilities that might be added in the future, e.g. support for MQTT over WebSocket (if they add it to the Java library) and potentially failover support. Whether this future benefit and increased flexibility is worth breaking compatibility with old inputs, is up to you. But I think I've talked myself out of trying to merge the two approaches.

**Comment by brudo** [comment]
@hanoch I forgot to tag you. See above; this is ready to proceed and the choice of which PR is with you.

**Comment by hanoch** [comment]
@brudo I will accept the current PR, so we can move forward.  that said, we need to make sure that the ports the user is defining in the url prop will be used, rather than the default 1883 for tcp and 8883 for ssl.

**Pull request merged**
